title: Zeyu Ding
description: Ph.D. Candidate in Statistics
theme: jekyll-theme-minimal

# 重要：添加这些配置
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# 确保这些路径设置正确
baseurl: ""
url: "https://zeyudsai.github.io"
