remote_theme: daattali/beautiful-jekyll

# Site settings
title: Zeyu Ding
author: Zeyu Ding
description: Portfolio & Research

# Navigation
navbar-links:
  About: "about"
  Projects: "projects"
  Publications: "publications"
  
# Colors
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"

# Social network
social-network-links:
  email: "your.email@example.com"
  github: zeyudsai
  linkedin: your-linkedin-username
  
# Advanced settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
plugins:
  - jekyll-sitemap
  - jekyll-gist
