remote_theme: pages-themes/minimal
title: Zeyu Ding
description: Ph.D. Candidate in Statistics
#logo: /assets/img/logo.png  # 如果你想添加个人照片

social:
  github: zeyudsai
  linkedin: zeyu-ding-sai
  email: zeyu.ding@tu-dortmund.de

#google_analytics: [Your tracking ID] # 可选

plugins:
  - jekyll-seo-tag
