remote_theme: pages-themes/minimal
title: Zeyu Ding
description: Ph.D. Candidate in Statistics | TU Dortmund
show_downloads: false

github:
  is_project_page: false

# 为页面添加元数据
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
