title: Zeyu Ding
description: Ph.D. Candidate in Statistics
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# 重要的配置
markdown: kramdown
kramdown:
  input: GFM

# 作者信息
author:
  name: Zeyu Ding
  email: zeyu.ding@tu-dortmund.de

# 网站设置
baseurl: ""
url: https://zeyudsai.github.io
