title: Zeyu Ding
description: Ph.D. Candidate in Statistics
theme: jekyll-theme-minimal

# 基本设置
show_downloads: false
#google_analytics: [Your tracking ID] # 可选

# 作者信息
author:
  name: Zeyu Ding
  email: zeyu.ding@tu-dortmund.de
